### ISSUE TITLE
Complete project files

### ISSUE THREAD

**Issue by h574641** [182719/Bachelor-Oppgave#3]
We have tried to use this project in this repo on github, but are having some problems since some of the files were not uploaded. Do you have the complete project stored somewhere and could you share it with us?

**Comment by ghost** [comment]
Hei, du kan laste ned hele scenen herfra: link fjernet

Fint om du gir beskjed når du har gjort det så jeg kan slå av lenken.

**Comment by h574641** [comment]
Hei, takk for hjelpen!

Har lastet den ned nå.

Martin
